### PR TITLE
Export PrettyOptions in ES6-import-friendly way

### LINKED ISSUE #189: Unexported interface PrettyOptions causes type-check error in @types/pino
This kind of breaks pino with `TS2694: Namespace '"/node_modules/pino-pretty/index"' has no exported member 'PrettyOptions'.`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L546

[image](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L546)

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #189

### CODE REVIEW

**Comment by kibertoad** [comment]
@squidini Could you please review?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by squidini** [comment]
Just checked in strict mode with es2020 module it works now. @kibertoad

**Comment by mcollina** [comment]
Done

**Pull request merged**
