### PR TITLE
fix: wrong array being iterated

### PR DESCRIPTION
**Pull request by rohit-gohri**
Saw this error while seeing the code as reference for https://github.com/pinojs/pino-http-print/issues/9

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
Can we cover this with a unit test?

**Comment by rohit-gohri** [comment]
> Can we cover this with a unit test?

I'm not sure how since this wasn't causing any errors/bugs, because of this check just below: https://github.com/rohit-gohri/pino-pretty/blob/585c0bb7999b6cfc52e06b1e951e267f8758b809/lib/utils.js#L315

**Comment by jsumners** [comment]
Compare an object that doesn't iterate correctly prior to the change with a known good output.

**Comment by rohit-gohri** [comment]
> Compare an object that doesn't iterate correctly prior to the change with a known good output.

That's what I'm saying, even though the wrong array was being iterated the output was already correct because the value was compared against undefined before doing anything with it:

https://github.com/rohit-gohri/pino-pretty/blob/585c0bb7999b6cfc52e06b1e951e267f8758b809/lib/utils.js#L310-L316

**Comment by mcollina** [comment]
If it access the wrong index, it could result printing the wrong value maybe? The test could verify if there are no spurious keys.

**Comment by mcollina** [comment]
Close with no activity.

**Pull request closed without merging**
