### PR TITLE
Fix broken circular reference handling when filtering

### PR DESCRIPTION
**Pull request by blaenk**
I updated from 4.7.1 to 5.0.1 and I kept getting an error regarding `rfdc`. Eventually tracked it down to this library. It seems like it was introduced in https://github.com/pinojs/pino-pretty/pull/180

```
/home/blaenk/code/app/bot/node_modules/rfdc/index.js:39
    if (o instanceof Date) return new Date(o)
          ^
RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:39:11)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
    at cloneArray (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:31:17)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:40:34)
    at cloneArray (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:31:17)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:52:25)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
```

It seems like the log is unconditionally "cloned" via rfdc when `ignore` is set in the options.

https://github.com/pinojs/pino-pretty/blob/357590425b1d0b23e4e92cbf985d5de0dae1c194/lib/utils.js#L474

By default, rfdc doesn't track circular references so naturally it gets stuck infinitely traversing the circular references.

It seems rfdc does have a feature to [track circular references](https://github.com/davidmarkclements/rfdc#circles-option) albeit at the cost of performance since it has the overhead of tracking the references. I think that's ok since pino-pretty is meant for development uses anyway (AFAIK), and we already handle circular references in other areas (stringifying https://github.com/pinojs/pino-pretty/pull/50).

I do know that this didn't used to be a problem in 4.7.1. I also know regular `console.log()` is able to handle this of course (it'll simply print something like `<ref *1>`).

I'm not very familiar with tape and this was already a bit of an unexpected time sink, so please feel free to directly push any further commits to this branch and take over.

### CODE REVIEW

**Comment by jsumners** [comment]
Can you clarify how circular data even makes it into `pino-pretty`? `pino-pretty` reads the log object _after_ `pino` (or whatever else) has already generated the NDJSON line. Given that JSON cannot contain circular references, I don't understand the situation in which this could occur.

**Comment by blaenk** [comment]
I couldn't tell you.

All I know is that it's broken at the moment when printing objects with circular references. Ideally a user doesn't print such objects to begin with, but sometimes it's not up to one and it's not realistic to expect one to manually excise each circular reference lest this library crash.

I do know that it's due to the use of `rfdc` as mentioned in the PR. Please see the included test.

**Comment by jsumners** [comment]
Can you present a minimal reproduction?

**Comment by blaenk** [comment]
https://github.com/blaenk/pino-repro

Output:

```
λ ~/code/pino-repro → main
» npm run build && npm start

> pino-repro@0.0.1 build /home/blaenk/code/pino-repro
> tsc -p .


> pino-repro@0.0.1 start /home/blaenk/code/pino-repro
> NODE_ENV=development node ./build/index.js

[2021-05-31 18:47:22.268] INFO: This is a test
[2021-05-31 18:47:22.271] INFO: Printing an object
    example: "value"
/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:39
    if (o instanceof Date) return new Date(o)
          ^

RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:39:11)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
    at clone (/home/blaenk/code/pino-repro/node_modules/rfdc/index.js:58:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pino-repro@0.0.1 start: `NODE_ENV=development node ./build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pino-repro@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/blaenk/.npm/_logs/2021-06-01T01_47_22_285Z-debug.log
```

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
> Can you clarify how circular data even makes it into `pino-pretty`? `pino-pretty` reads the log object _after_ `pino` (or whatever else) has already generated the NDJSON line. Given that JSON cannot contain circular references, I don't understand the situation in which this could occur.

that's not strictly true. It reads the actual objects when we pass in `prettyPrint: true` in pino.

FWIW, I would look to remove that option in v8 or anything and just rely on the transport system (or alias it to the transport system). We can remove so much complexity.

**Review by jsumners — APPROVED** [review]

**Pull request merged**
