### PR TITLE
Update to sonic-boom@2.2.1

### PR DESCRIPTION
**Pull request by aaestrada**
This pr will Update to sonic-boom@2.2.1

### CODE REVIEW

**Comment by aaestrada** [comment]
Let me know if there is any request changes!

**Comment by kibertoad** [comment]
What is the rationale behind this change?

**Comment by aaestrada** [comment]
> What is the rationale behind this change?



The pino library is using ` "sonic-boom": "^2.2.1",` as a [dependency in the package.json](https://github.com/pinojs/pino/blob/master/package.json#L113)

so this will work better with the same version!

**Comment by mcollina** [comment]
npm will resolve to be the same version when it installs.

**Pull request closed without merging**
