### PR TITLE
Fix/remove extra space

### PR DESCRIPTION
**Pull request by arthurw1**
This PR addresses #140 

## Update
This PR removes all alignment spaces for log level constants.

---

The change here is simply to revert #135 

The extra spaces highlighted in #140 was caused by using `\t` as delimiter. 

Result:
image

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jsumners** [comment]
This is basically creating churn between space formatting and tab formatting. @Zirak introduced space formatting because they found it easier to read the formatted output. @dublx converted it to tab based formatting for more consistency. I think we need a better solution than alternating between these two every few months.

**Comment by mcollina** [comment]
@jsumners wdyt? should we land this or not?

**Comment by jsumners** [comment]
> @jsumners wdyt? should we land this or not?

I really don't think so. Not until the parties involved that have been interested in this formatting speak up (@Zirak and @dublx).

My opinion is we completely remove this alignment formatting feature completely if no one is able to propose a solution that works as everyone expects. It seems to me that the issue is down to the terminal emulator and font being used and how the present `\t` and ` `.

I just don't know how we can satisfy all desires here easily. Reverting the `\t` change will cause #135 to be an issue again.

**Comment by dublx** [comment]
Aye, I totally agree. 
I'm burned out of time to work on this unfortunately but in terms of choice i'd go with investing time to make \t work well for most people.

**Comment by mcollina** [comment]
I think we should revert the feature.

**Comment by jsumners** [comment]
@arthurw1 would you like to create a PR that completely reverts the space formatting feature?

**Comment by arthurw1** [comment]
@jsumners Yes I can take that on. I will simply make the changes on top of this current branch if that's ok.

**Comment by jsumners** [comment]
That is fine.

**Comment by arthurw1** [comment]
@jsumners @mcollina PR updated based on latest decision

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM

**Comment by jsumners** [comment]
@mcollina do we think this is patch, minor, or major? I think I could make an argument for any one of them.

**Comment by mcollina** [comment]
I would land this as a minor. If you are parsing this manually you are doing it wrong.

**Pull request merged**
