### PR TITLE
fix: dateformat migrated to esm

### PR DESCRIPTION
**Pull request by climba03003**
As `dateformat` moved from `CJS` to `ESM`.
Change the version to `~` flag to prevent further impact.

Related to https://github.com/pinojs/pino/pull/1137

### CODE REVIEW

**Comment by climba03003** [comment]
It seems that coveralls is blocking the CI. `405` problems again.

**Comment by kibertoad** [comment]
Should be finished soon: https://status.coveralls.io/?utm_source=embed

**Comment by climba03003** [comment]
I will either use [`continue-on-error`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) for `Coveralls` or disable it until the maintenance is over.

Coveralls should not be the blocker for CI.

**Comment by kibertoad** [comment]
continue-on-error sounds like a great idea!

**Comment by kibertoad** [comment]
@climba03003 Can you try 4.6.2? If I'm reading https://github.com/felixge/node-dateformat/releases right, looks like they realized their mistake.

**Comment by climba03003** [comment]
> 
> 
> @climba03003 Can you try 4.6.2? If I'm reading https://github.com/felixge/node-dateformat/releases right, looks like they realized their mistake.

@kibertoad I will use 4.6.3 as it is the latest in `npmjs`. And I have updated the CI to skip or allow all the stage of coveralls to fail.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
