### PR TITLE
Added ident to ERROR message (#113)

### PR DESCRIPTION
**Pull request by d52b8**
* it also needed to add quotation marks (or delete them from INFO)

### CODE REVIEW

**Comment by d52b8** [comment]
@jsumners I'd love to but I don't know how

**Comment by jsumners** [comment]
Just in general or do you have some issue with this project’s test suite?

**Comment by d52b8** [comment]
General

**Comment by jsumners** [comment]
The short version is that a unit test is a block of code that verifies application does what it is supposed to do. The tests for this module verify that specific input results in desired output. For example, the change in this PR causes existing tests to fail -- https://github.com/pinojs/pino-pretty/pull/114/checks?check_run_id=831707313#step:6:399 . This quickly shows me that I cannot merge the PR as it is written. Additionally, any new code written should be covered by a new test that verifies its functionality.

This module follows the npm standard of `npm test` for running tests. Executing the command `npm test` will run the test suite and report successes and failures. The test suite code is found in https://github.com/pinojs/pino-pretty/tree/62a5f01d31aef4ca8ff69a08180080bd88506c2c/test

**Comment by mcollina** [comment]
Closing for no activity, feel free to reopen if you are still interested.

**Pull request closed without merging**
