### PR TITLE
Properly ignore level; dont show `;` if nothing preceeds it

### LINKED ISSUE #60: can't ignore level
Using the new `ignore` parameter, doesn't seem to work for `level`:

```
echo '{"level":30,"time":1522431328992,"msg":"hello world","pid":42,"hostname":"foo","v":1, "name":"pou"}' | node bin.js -ti level
[2018-03-30 17:35:28.992 +0000] USERLVL (pou/42 on foo): hello world
```

i.e., it displays `USERLVL` instead of nothing.  Here's the line that fails:

```
levels.hasOwnProperty(log.level)
  ? color[log.level](levels[log.level])
  : color.default(levels.default)
```

`log.level` here is undefined, so it falls back to USERLVL.

Also, kind of related - if you tell it to ignore everything before the `:` it'll still show the `:`

### PR DESCRIPTION
**Pull request by tswaters**
Fixes #60

### CODE REVIEW

**Comment by tswaters** [comment]
Hopefully CI passes.  I had some errors running on my localhost, possibly relating to windows.  A few of the error case tests were failing -- but without this change they were still failing so who knows.

**Comment by jsumners** [comment]
Is this problem present in `pino-pretty@next`?

**Comment by tswaters** [comment]
```"pino-pretty": "^2.6.0"```

**Comment by tswaters** [comment]
@jsumners this problem does NOT show on `pino-pretty@next`

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-pretty/releases/tag/v2.6.1

**Comment by tswaters** [comment]
Thanks!

**Pull request merged**
