### PR TITLE
Add type definition for the 'sync' option

### PR DESCRIPTION
**Pull request by OnkelTem**
Adding types for #297 

cc @mcollina  :)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test? We use tsd.

**Comment by OnkelTem** [comment]
Matteo, following `test/types/pino-pretty.test-d.ts` style, it would be just:

```patch
diff --git a/test/types/pino-pretty.test-d.ts b/test/types/pino-pretty.test-d.ts
index 72bdd8c..90a3405 100644
--- a/test/types/pino-pretty.test-d.ts
+++ b/test/types/pino-pretty.test-d.ts
@@ -27,7 +27,8 @@ const options: PinoPretty.PrettyOptions = {
     key: (value) => {
       return value.toString().toUpperCase();
     }
-  }
+  },
+  sync: false,
 };
 
 const options2: PrettyOptions = {
@@ -49,7 +50,8 @@ const options2: PrettyOptions = {
     key: (value) => {
       return value.toString().toUpperCase();
     }
-  }
+  },
+  sync: false,
 };
 
 expectType<PrettyStream>(pretty(options));
```

Did I get it right and that's what you meant?

**Comment by mcollina** [comment]
Yes, exactly

**Comment by OnkelTem** [comment]
Hi! Have I done it already? Or I missed something? Not quite sure what I'm looking at: 

image

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
