### PR TITLE
fix: null stack error

### PR DESCRIPTION
**Pull request by ilyaztsv**
Fixed `null stack` problem mentioned here: https://github.com/pinojs/pino-pretty/issues/1#issuecomment-378165197

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by ilyaztsv** [comment]
> Can you please add a unit test?

Sorry, my bad. Will do it

**Comment by ilyaztsv** [comment]
@mcollina I've added unit test :)

**Comment by jsumners** [comment]
Thank you for helping out @ilyaztsv

**Comment by ilyaztsv** [comment]
@jsumners no problem 😄

**Pull request merged**
