### PR TITLE
Add TypeScript types

### PR DESCRIPTION
**Pull request by kibertoad**
Part of effort to do https://github.com/pinojs/pino/pull/913

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by squidini** [comment]
This kind of breaks pino with `TS2694: Namespace '"/node_modules/pino-pretty/index"' has no exported member 'PrettyOptions'.` #189

**Comment by kibertoad** [comment]
@squidini Thank you for the bug report! Will fix this today

**Comment by kibertoad** [comment]
@squidini Isn't it actually available on a namespace, though?

**Comment by squidini** [comment]
@kibertoad it actually is available in a namespace.
But defining namespace this way breaks support of `esnext` modules.
I managed to resolve this issue by declaring everything in a module.

```ts
declare module "pino-pretty" {
  export interface PrettyOptions {
```

This is my tsconfig:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
  }
}
```

**Comment by kibertoad** [comment]
Wonder why it got broken, though. Wasn't it not exported directly in the past either? See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino-pretty/index.d.ts

**Comment by squidini** [comment]
Probably it wasn't working with es2020 modules before. I need to verify this.

**Comment by kibertoad** [comment]
@squidini Would appreciate it! Will still try to make it work with both options, though.

**Pull request merged**
