### PR TITLE
feat: align log levels

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hello,

It's been several times that I find it unfortunate that the logs are not aligned. I searched how to align logs and I found this PR #47 (3 years ago) that fixes the issue but this fix has disappeared from master.

The current PR fixes the issue again :) It is more beautiful with ^^

Thank you for your work!

### CODE REVIEW

**Comment by mcollina** [comment]
I don't think this is doable as we had to revert because it created more work than necessary.

wdyt @jsumners?

**Comment by jsumners** [comment]
Thank you for your contribution, but this feature introduces more problems than it solves. This feature makes maintenance very difficult. We cannot accept this feature.

**Comment by Tchoupinax** [comment]
Thank you for your answer.

Could you enum exemples of point that makes maintenance difficult ? (For my information and maybe have a trace for another people)

**Comment by jsumners** [comment]
Just search back through the issues and pull requests for the ones around alignment.

**Pull request closed without merging**
